version: '2'
services:
  cms:
    build:
      context: ./docker-src/cms
    mem_limit: 512M
    volumes:
      - .:/var/www
    env_file: environment
    environment:
      - CONNECTBACK=on
    links:
      - db
      - memcache
    networks:
      - connector

  db:
    image: mariadb:latest
    mem_limit: 512M
    env_file: environment
    volumes:
      - ./docker-src/db/conf:/etc/mysql/conf.d
      - database:/var/lib/mysql
    networks:
      - connector

  memcache:
    image: memcached:latest
    mem_limit: 128M
    environment:
      - MEMCACHED_SERVER=memcached:11211
    networks:
      - connector

networks:
  connector:

volumes:
  database: {}
